baseURL: "https://annalhq.github.io/"
languageCode: en-us
title: annenso
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
mainsections: ["blog"]

minify:
  disableXML: true
  # minifyOutput: true

params:
  env: production
  title: annalhq
  description: "personal site"
  keywords: [Blog, Portfolio]
  defaultTheme: dark
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false

  label:
    text: "annenso"

  # profile-mode
  profileMode:
    enabled: false
    title: PaperMod
    buttons:
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Annalhq Shaikh"
    Content: >
      I am currently doing my undergrad with a focus on mathematics and machine learning.
      My research interests lie in the intersection of these fields,
      where I'm interested in exploring how mathematical structures can be leveraged to create more interpretable models.

  socialIcons:
    - name: twitter
      url: "https://x.com/Annalhq24"
    - name: stackoverflow
      url: "https://stackoverflow.com"
    - name: github
      url: "https://github.com/annalhq"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    limit: 10 # refer: https://www.fusejs.io/api/methods.html#search
    keys: ["title", "permalink", "summary", "content"]

  outputs:
  home:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: archives
      name: archives
      url: /archives/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: blog
      name: blog
      url: /blog/
      weight: 30
    - identifier: search
      url: /search/
      weight: 40

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
